spring:
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 8888
    url: jdbc:mysql://192.168.43.198:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  jpa:
    show-sql: true
  
  redis:
    host: 192.168.43.198
    port: 6379
  
  rabbitmq:
    host: 192.168.43.198
    port: 5672
    password: guest
    username: guest


